#!/usr/bin/with-contenv bash

if which node > /dev/null
then
    echo "**** node is installed, skipping... ****"
else
    echo "**** install runtime packages ****"
    echo "**** apt-get update ****"
    apt-get update
    echo "**** install libatomic1, file, nginx ****"
    apt-get install -y libatomic1 file nginx
    echo "**** install 'n' ****"
    curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
    echo "**** install nodejs ****"
    bash n lts
fi

