{
 "title": "ClusterPlex",
 "description": "Monitoring dashboard for ClusterPlex deployments",
 "tags": [
  "clusterplex",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Active Workers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "workers_active" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(worker_load_cpu) by (worker_name)",
     "legendFormat": "{{worker_name}}"
    }
   ]
  },
  {
   "title": "Rank",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(worker_load_rank) by (worker_name)",
     "legendFormat": "{{worker_name}}"
    }
   ]
  },
  {
   "title": "Job Posters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "job_posters_active" }
   ]
  },
  {
   "title": "Tasks Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(worker_load_tasks) by (worker_name)",
     "legendFormat": "{{worker_name}}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(jobs_succeeded[30d])", "legendFormat": "Succeeded" },
    { "expr": "increase(jobs_failed[30d])", "legendFormat": "Failed" },
    { "expr": "increase(jobs_killed[30d])", "legendFormat": "Cancelled" }
   ]
  },
  {
   "title": "Posted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "increase(jobs_posted[1d])" }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "increase(jobs_completed[1d])" }
   ]
  }
 ]
}