#!/usr/bin/with-contenv bash

if which node > /dev/null
then
    echo "**** node is installed, skipping... ****"
else
    echo "**** install runtime packages ****"
    echo "**** apt-get update ****"
    apt-get update
    echo "**** install binutils, libatomic1, file, unzip ****"
    apt-get install -y binutils libatomic1 file unzip
    echo "**** install 'n' ****"
    curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
    echo "**** install nodejs ****"
    bash n lts
    if [ -n "$EXTRA_APT_INSTALLS" ]; then
        echo "**** EXTRA_APT_INSTALLS is set, installing '${EXTRA_APT_INSTALLS}' ... ****"
        apt-get install -y $EXTRA_APT_INSTALLS
    else
        echo "**** EXTRA_APT_INSTALLS is not set, skipping... ****"
    fi
fi

