# This is a basic workflow to help you get started with Actions

name: DockerMod Builds

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'dev'
      - 'experimental'
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'charts/**'
  pull_request:
    branches:
      - 'master'
      - 'dev'
    paths-ignore:
      - 'charts/**'

permissions:
  contents: read
  packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-pms-docker-mod:
    runs-on: ubuntu-latest
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta for PMS-dockermod
        id: meta_pms_dockermod
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            pabloromeo/clusterplex_dockermod
            ghcr.io/pabloromeo/clusterplex_dockermod
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push PMS-dockermod
        uses: docker/build-push-action@v6
        with:
          context: ./pms
          file: ./pms/docker-mod/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_pms_dockermod.outputs.tags }}
          labels: ${{ steps.meta_pms_dockermod.outputs.labels }}
      - name: Docker Hub Description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: pabloromeo/clusterplex_dockermod
          readme-filepath: ./README.md
          short-description: "ClusterPlex Dockermod for the LinuxServer/Plex image"

  build-worker-docker-mod:
    runs-on: ubuntu-latest
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta for worker-dockermod
        id: meta_worker_dockermod
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            pabloromeo/clusterplex_worker_dockermod
            ghcr.io/pabloromeo/clusterplex_worker_dockermod
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push worker-dockermod
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          file: ./worker/docker-mod/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_worker_dockermod.outputs.tags }}
          labels: ${{ steps.meta_worker_dockermod.outputs.labels }}
      - name: Docker Hub Description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: pabloromeo/clusterplex_worker_dockermod
          readme-filepath: ./README.md
          short-description: "ClusterPlex Worker Dockermod for the LinuxServer/Plex image"
